#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Ngiinx to listen on port 80
#and return "Hello World!" on the root path
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
service nginx start
