#!/pusr/bin/env bash

# Update the system
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure the redirection
sudo echo "server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 http://example.com/new-page;
    }

    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}" | sudo tee /etc/nginx/sites-available/redirect

# Enable the redirection site
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
