#!/usr/bin/env bash
#Configures ubuntu server with
#localhost resolve to 127.0.0.2
#facebook.com resolve to 8.8.8.8
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
