#!/usr/bin/env bash
#Configures ubuntu server with
#localhost resolve to 127.0.0.2
#facebook.com resolve to 8.8.8.8
#!/bin/bash

# Set up the localhost resolution
sudo sed -i 's/^127\.0\.0\.1\s*localhost$/127.0.0.2 localhost/' /etc/hosts

# Set up the Facebook resolution
sudo sed -i 's/^#*\s*8\.8\.8\.8\s*facebook\.com$/8.8.8.8 facebook.com/' /etc/hosts
