#!/usr/bin/env bash
# script to configure broken container to work with nginx at port 8080

sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf

# Check if port 8080 is already in use
if nc -z -v -w5 0.0.0.0 8080; then
    echo "Port 8080 is already in use. Exiting."
    exit 1
fi

# Update nginx configuration for port 8080 and all active IPs
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
EOF

# Create a symbolic link to enable the configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart nginx to apply changes
service nginx restart
